groups:
  - name: custom_rule
    rules:
      - record: node_filesystem_freemem
        expr: 100 - (100*node_filesystem_free_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"})
  - name: example_alert
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
